#!/bin/sh

if [ "$CI" = true ]; then
  exit 0
fi

# source the root env for environment
if [ -f ".env" ]; then
  source .env
fi

if [ -z "$ENVIRONMENT" ]; then
  echo "ENVIRONMENT env variable must be set in root \`.env\` file"
  exit 1
fi

# load config
CONFIG=$(cat libs/environment/config.json)

# MARK: copy secrets

# load infisical domain and project id
INFISICAL_DOMAIN=$(echo $CONFIG | jq -r '.infisicalDomain')
INFISICAL_PROJECT_ID=$(echo $CONFIG | jq -r '.infisicalProjectId')

# infisical for some reason only accepts 'dev' and 'prod' as env names
INFISICAL_ENVIRONMENT_MAP='{"development": "dev", "production": "prod"}'
INFISICAL_ENVIRONMENT=$(echo $INFISICAL_ENVIRONMENT_MAP | jq -r ".$ENVIRONMENT")

# iterate over apps and load secrets for each app
APPS=$(echo $CONFIG | jq -r '.apps | keys[]')
for APP in $APPS; do
  echo "# ! IMPORTANT: This .env file is auto-generated by libs/environment." > apps/$APP/.env.local
  echo "# ! Do not edit this file directly." >> apps/$APP/.env.local
  echo "ENVIRONMENT=$ENVIRONMENT" >> apps/$APP/.env.local

  HAS_SECRETS=$(echo $CONFIG | jq -r ".apps.$APP.hasSecrets")
  if [ "$HAS_SECRETS" = false ]; then
    # still wipe 
    continue
  fi

  echo "Loading secrets for app: $APP"

  SECRETS=$(
    infisical secrets \
      --domain $INFISICAL_DOMAIN \
      --env $INFISICAL_ENVIRONMENT \
      --projectId $INFISICAL_PROJECT_ID \
      --path /$APP \
      --output dotenv
  )

  echo "$SECRETS" >> apps/$APP/.env.local
done

# MARK: copy convex variables

CONVEX_APP_DIRECTORY=$(echo $CONFIG | jq -r '.convexProjectDirectory')

if [ "$ENVIRONMENT" = "PRODUCTION" ]; then
  echo "Skipping apollo environment variables for production environment"
  exit 0
fi

if [ ! -f "$CONVEX_APP_DIRECTORY/.env.local" ]; then
  echo "apollo .env.local missing"
  exit 1
fi

. "$CONVEX_APP_DIRECTORY/.env.local"
if [ -z "$CONVEX_URL" ] || [ -z "$CONVEX_SITE_URL" ]; then
  echo "CONVEX_URL or CONVEX_SITE_URL missing"
  exit 1
fi

CONFIG=$(cat libs/environment/config.json)

APPS=$(echo $CONFIG | jq -r '.apps | keys[]')
for APP in $APPS; do
  HAS_CONVEX=$(echo $CONFIG | jq -r ".apps.$APP.hasConvex")
  if [ "$HAS_CONVEX" = false ]; then
    continue
  fi

  echo "Loading convex env variables for app: $APP"
  PUBLIC_PREFIX=$(echo $CONFIG | jq -r ".apps.$APP.publicPrefix // \"\"")
  echo "" >> apps/$APP/.env.local
  echo "# convex variables" >> apps/$APP/.env.local
  echo "${PUBLIC_PREFIX}CONVEX_URL=$CONVEX_URL" >> apps/$APP/.env.local
  echo "${PUBLIC_PREFIX}CONVEX_SITE_URL=$CONVEX_SITE_URL" >> apps/$APP/.env.local
done
